#+TITLE: Accidental Inventions

** 
# Fireworks

Created in China around 2000 years ago, while experimenting with a combination of charcoal, saltpeter and sulfur. This combination exploded, resulting in fireworks.

# Velcro

George de Mestral, a Swiss engineer, was walking his dog in 1948, when he noticed burrs stuck to his dog’s fur. He examined them under a microscope and noticed they were composed of tiny hooks that held onto fur and fabric. He spent years experimenting with textiles to recreate that, and finally made some progress when nylon was invented. The first to take note were NASA, 20 years after George had invented the Velcro.

# Shatter-Proof Glass

In 1903, French chemist Edouard Benedictus was in his lab and accidentally dropped a flask. When the flask didn’t shatter, he checked his notes to see what was in it. He noted that plastic cellulose nitrate was in the flask, and prevented it from shattering on impact. He went on to develop Safety Glass.

# Super Glue

In 1942, Dr. Harry Coover was trying to create a sight for a precision rifle, but failed. Instead, he created a substance called cyanoacrylate, that stuck to everything. Six years later, when trying to design new airplane canopies, he failed again because of the same substance. This time, he realized he could create a strong bond between two items without using heat. In 1958, he patented his glue and called it Super Glue

# Tea Bags

In the early 1900s, an American tea merchant called Thomas Sullivan sent samples of his tea to costumers, in silken bags. The costumers thought the bags were meant to replace metal tea infusers, and they put the bags in the teapots. After receiving some complaints that the silk mesh was too fine, Thomas had the idea of making the bags out of gauze. During the 1920s, it went viral.

# Penicillin

# Source

[Fun Facts About Accidental Inventions - TellmeWhyFacts | Science News](https://tellmewhyfacts.com/fun-facts-about-accidental-inventions/)
