#+TITLE: Airglow

*** #Science #Space #Chemistry
** Definition

Airglow is a faint emission of light in a planet’s atmosphere. On Earth, this causes the night sky to never be fully dark. It is generally bluish in color.
**
** History

First identified in 1868 by Swedish physicist Anders Ångström.

The phenomenon has since been documented, studied in laboratory and confirmed by astronomers.
**
** Causes

Various chemical reactions happening in the atmosphere release electromagnetic energy or photons. They aren’t visible during the day because of the Sun’s glare.
**
** Examples:

- Recombination of atoms photoionized by the Sun
- Luminescence caused by cosmic rays hitting the upper atmosphere
- [Chemiluminescence](https://www.notion.so/Chemiluminescence-0722248c0aa74293bf6d6b8c0c3fba18)  caused by oxygen and nitrogen reacting with hydroxyl free radicals
- An atom of nitrogen combines with one of oxygen to form a molecule called nitric oxide (NO). In the process, a photon is emitted.
**
** Source

[Airglow](https://encyclopedia.thefreedictionary.com/Airglow)**
